# Generated by Django 2.2.2 on 2019-06-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Сообщение')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
            ],
        ),
    ]
